version: '3.8'

services:

  api:
    build: .

    ports:
      - "8080:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=StudentManagementDB;User=sa;Password=YourStrong@Password123;TrustServerCertificate=True
      - JwtSettings__SecretKey=YourSuperSecretKeyHere_MakeItLong_AtLeast32Chars!
      - JwtSettings__Issuer=StudentManagementSystem
      - JwtSettings__Audience=StudentManagementUsers

    depends_on:
      - db

    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123

    ports:
      - "1434:1433"

    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: